# Generated by Django 6.0.3 on 2026-05-19 09:24

import django.db.models.deletion
from django.db import migrations, models


def truncate_licencias_funcionamiento(apps, schema_editor):
    schema_editor.execute("TRUNCATE TABLE licencias_funcionamiento CASCADE")


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0004_tipoprocedimientotupa_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
        migrations.RunPython(truncate_licencias_funcionamiento, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='licenciafuncionamiento',
            name='actividad',
            field=models.ForeignKey(db_column='actividad_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.actividad'),
        ),
    ]
