# Generated by Django 6.0.3 on 2026-05-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0005_actividades_fk_licencias_funcionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='requiere_auth_sectorial',
            field=models.BooleanField(default=False),
        ),
    ]
